version: '3'
services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    restart: always
    environment:
    - POSTGRES_PASSWORD=postgres
  admin:
    image: dpage/pgadmin4
    ports:
    - "5433:80"
    environment:
    - PGADMIN_DEFAULT_EMAIL=karolistarasaitis@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=123456
    